-- 1 NEGOCIOS DUPLICADOS
DELETE
FROM FIP.FIP_DIARIO_NEGOCIOS FRC WHERE
    (FRC.NUM_CTA_CREDITO, FRC.COD_CLIENTE, FRC.COD_EXTRAFIN, FRC.FECHA_CORTE, FRC.ROWID) IN
    (
      SELECT FN.NUM_CTA_CREDITO, FN.COD_CLIENTE, FN.COD_EXTRAFIN, FN.FECHA_CORTE, MIN(FN.ROWID)
        FROM FIP.FIP_DIARIO_NEGOCIOS FN
       WHERE FN.FECHA_CORTE = TO_DATE('19062020', 'DDMMYYYY')
         AND FN.CODIGO_PATRIMONIO = 10
         HAVING COUNT(1) > 1
         GROUP BY FN.NUM_CTA_CREDITO, FN.COD_CLIENTE, FN.COD_EXTRAFIN, FN.FECHA_CORTE
    )
    AND FRC.CODIGO_PATRIMONIO = 10
    AND FRC.FECHA_CORTE = TO_DATE('19062020', 'DDMMYYYY');
COMMIT;
