-- 1 CUOTAS SIN NEGOCIO
DELETE
    FROM FIP.FIP_DIARIO_CUOTANEGOCIOS FDC
    WHERE FDC.FECHA_CORTE = TO_DATE('13062020', 'ddmmyyyy')
     AND FDC.CODIGO_PATRIMONIO = 4
     AND NOT EXISTS (
        SELECT 1
            FROM FIP.FIP_DIARIO_NEGOCIOS FDN
            WHERE FDN.NUM_CTA_CREDITO = FDC.NUM_CTA_CREDITO
             AND FDN.COD_CLIENTE = FDC.COD_CLIENTE
             AND FDN.COD_EXTRAFIN = FDC.COD_EXTRAFIN
             AND FDN.COD_EMPRESA = FDC.COD_EMPRESA
             AND FDN.FECHA_CORTE = FDC.FECHA_CORTE
             AND FDN.CODIGO_PATRIMONIO = FDC.CODIGO_PATRIMONIO);
COMMIT;
